import type { Locale } from "@/lib/i18n";

const labels = {
  de: [
    {
      cta: "Spenden ansehen",
      eyebrow: "Direkte Unterstützung",
      href: "#donar",
      id: "donar",
      title: "Spenden",
    },
    {
      cta: "Mitglied werden",
      eyebrow: "Regelmäßige Hilfe",
      href: "#socio",
      id: "socio",
      title: "Mitglied werden",
    },
    {
      cta: "Zu Teaming",
      eyebrow: "Mikrospende",
      href: "#teaming",
      id: "teaming",
      title: "Teaming beitreten",
    },
    {
      cta: "Pflegestelle ansehen",
      eyebrow: "Vorübergehende Pflege",
      href: "#acogida",
      id: "acogida",
      title: "Pflegestelle werden",
    },
    {
      cta: "Patenschaften ansehen",
      eyebrow: "Laufende Hilfe",
      href: "/apadrina",
      id: "apadrinar",
      title: "Tierpatenschaft übernehmen",
    },
    {
      cta: "Freiwilligenarbeit ansehen",
      eyebrow: "Aktive Beteiligung",
      href: "#voluntariado",
      id: "voluntariado",
      title: "Freiwillig helfen",
    },
    {
      cta: "Teilen ansehen",
      eyebrow: "Netzwerk und Sichtbarkeit",
      href: "#difundir",
      id: "difundir",
      title: "Teilen und mithelfen",
    },
  ],
  en: [
    {
      cta: "See donations",
      eyebrow: "Direct contribution",
      href: "#donar",
      id: "donar",
      title: "Donate",
    },
    {
      cta: "Become a member",
      eyebrow: "Stable support",
      href: "#socio",
      id: "socio",
      title: "Become a member",
    },
    {
      cta: "Go to Teaming",
      eyebrow: "Micro donation",
      href: "#teaming",
      id: "teaming",
      title: "Join Teaming",
    },
    {
      cta: "See fostering",
      eyebrow: "Temporary foster",
      href: "#acogida",
      id: "acogida",
      title: "Become a foster home",
    },
    {
      cta: "See sponsorship",
      eyebrow: "Ongoing support",
      href: "/apadrina",
      id: "apadrinar",
      title: "Sponsor an animal",
    },
    {
      cta: "See volunteering",
      eyebrow: "Active participation",
      href: "#voluntariado",
      id: "voluntariado",
      title: "Volunteer",
    },
    {
      cta: "See outreach",
      eyebrow: "Visibility and network",
      href: "#difundir",
      id: "difundir",
      title: "Spread the word and help",
    },
  ],
  es: [
    {
      cta: "Ver donaciones",
      eyebrow: "Aportación directa",
      href: "#donar",
      id: "donar",
      title: "Donar",
    },
    {
      cta: "Hazte socio",
      eyebrow: "Apoyo estable",
      href: "#socio",
      id: "socio",
      title: "Hazte socio",
    },
    {
      cta: "Ir a Teaming",
      eyebrow: "Microdonación",
      href: "#teaming",
      id: "teaming",
      title: "Unirse a Teaming",
    },
    {
      cta: "Ver acogida",
      eyebrow: "Acogida temporal",
      href: "#acogida",
      id: "acogida",
      title: "Ser casa de acogida",
    },
    {
      cta: "Ver apadrinamiento",
      eyebrow: "Apoyo continuado",
      href: "/apadrina",
      id: "apadrinar",
      title: "Apadrinar un animal",
    },
    {
      cta: "Ver voluntariado",
      eyebrow: "Participación activa",
      href: "#voluntariado",
      id: "voluntariado",
      title: "Ser voluntario",
    },
    {
      cta: "Ver difusión",
      eyebrow: "Difusión y red",
      href: "#difundir",
      id: "difundir",
      title: "Difundir y colaborar",
    },
  ],
} as const;

export const getHelpOptions = (locale: Locale) => labels[locale];
